@startuml
skinparam handwritten false
skinparam shadow false
skinparam defaultFontName Arial
skinparam roundCorner 8
hide stereotypes

' Paleta Pro
!define COLOR_ADMIN #1A252F
!define COLOR_USER #21618C
!define COLOR_APP #1E8449
!define COLOR_BG #F4F6F6

skinparam actor {
    BackgroundColor COLOR_ADMIN
    BorderColor COLOR_ADMIN
    FontColor COLOR_ADMIN
    FontSize 14
    FontStyle bold
}

skinparam usecase {
    BackgroundColor White
    BorderColor COLOR_ADMIN
    ArrowColor COLOR_ADMIN
    FontSize 12
    FontStyle bold
}

skinparam usecase<<Access>> {
    BackgroundColor COLOR_APP
    BorderColor COLOR_APP
    FontColor White
}

skinparam rectangle {
    BackgroundColor COLOR_BG
    BorderColor #AEB6BF
    FontColor COLOR_ADMIN
    FontStyle bold
}

top to bottom direction

actor "Administrador\n(SysAdmin / Dev)" as Admin
actor "Usuario Final\n(Navegador Web)" as User

rectangle "Sistema NEBULA" {
    usecase "**Configurar Hardening**\n(UFW, SSH, Fail2Ban)" as UC1
    usecase "**Instalar Dependencias**\n(Docker Engine)" as UC2
    usecase "**Desplegar Aplicación**\n(Docker Compose)" as UC3
    usecase "**Configurar Proxy & SSL**\n(Nginx Proxy Manager)" as UC4
    usecase "**Monitorizar Sistema**\n(Netdata)" as UC5
    usecase "**Realizar Backups**\n(Configuraciones)" as UC6
    
    usecase "**Acceder a App Web**\n(HTTPS Seguro)" as UC7 <<Access>>

    UC1 -[hidden]-> UC2
    UC2 -[hidden]-> UC3
    UC3 -[hidden]-> UC4
    UC4 -[hidden]-> UC5
    UC5 -[hidden]-> UC6
    UC6 -[hidden]-> UC7
}

Admin -[#1A252F,thickness=2]-> UC1
Admin -[#1A252F,thickness=2]-> UC2
Admin -[#1A252F,thickness=2]-> UC3
Admin -[#1A252F,thickness=2]-> UC4
Admin -[#1A252F,thickness=2]-> UC5
Admin -[#1A252F,thickness=2]-> UC6

User -[#1E8449,thickness=2]up-> UC7 : **Petición HTTPS**

UC7 .[#566573,thickness=1]down.> UC3 : **<<depends on>>**
UC7 .[#566573,thickness=1]down.> UC4 : **<<depends on>>**
@enduml
